---
language: ruby
bundler_args: --without development system_tests
before_install: rm Gemfile.lock || true
matrix:
  include:
  - rvm: 2.1
    env: PUPPET_GEM_VERSION="~> 3.0"   STRICT_VARIABLES=yes
  - rvm: 2.1
    env: PUPPET_GEM_VERSION="~> 4.0"   STRICT_VARIABLES=yes

  # the skeleton can't be tested on puppet 3.2.x to 3.5.x because the option to
  # skip the interview was only added in 3.6
  #
  # https://github.com/puppetlabs/puppet/commit/2c0456e5798046579daefe827262e23547cfe403
  # https://tickets.puppetlabs.com/browse/PUP-2284
  - rvm: 2.1
    env: PUPPET_GEM_VERSION="~> 3.6.0" STRICT_VARIABLES=yes
  - rvm: 2.1
    env: PUPPET_GEM_VERSION="~> 3.7.0" STRICT_VARIABLES=yes
  - rvm: 2.1
    env: PUPPET_GEM_VERSION="~> 3.8.0" STRICT_VARIABLES=yes
  - rvm: 2.1
    env: PUPPET_GEM_VERSION="~> 4.0.0" STRICT_VARIABLES=yes
  - rvm: 2.1
    env: PUPPET_GEM_VERSION="~> 4.1.0" STRICT_VARIABLES=yes
  - rvm: 2.1
    env: PUPPET_GEM_VERSION="~> 4.2.0" STRICT_VARIABLES=yes
  - rvm: 2.1
    env: PUPPET_GEM_VERSION="~> 4.3.0" STRICT_VARIABLES=yes
  - rvm: 2.1
    env: PUPPET_GEM_VERSION="~> 4.4.0" STRICT_VARIABLES=yes
  - rvm: 2.1
    env: PUPPET_GEM_VERSION="~> 4.5.0" STRICT_VARIABLES=yes
  - rvm: 2.1
    env: PUPPET_GEM_VERSION="~> 4.6.0" STRICT_VARIABLES=yes
script:
  - ./test.sh
notifications:
  email: false
